server:
  port: 9999

spring:
  application:
    name: es-article
  redis:
    host: 122.51.159.21
    port: 6379
    password: redis_password

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.159.21:3306/leadnews_article?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.common.article.pojos

#自定义elasticsearch连接配置
elasticsearch:
  host: 192.168.122.133
  port: 9200
